"""Initial 10 entity schema

Revision ID: 9930e188d00a
Revises: 
Create Date: 2026-09-14 11:48:49.299186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import database.base


# revision identifiers, used by Alembic.
revision: str = '9930e188d00a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plant_species',
    sa.Column('id', database.base.GUID(), nullable=False),
    sa.Column('common_name', sa.String(length=255), nullable=False),
    sa.Column('scientific_name', sa.String(length=255), nullable=True),
    sa.Column('aliases', sa.JSON(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('difficulty', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_indoor_suitable', sa.Boolean(), nullable=True),
    sa.Column('is_outdoor_suitable', sa.Boolean(), nullable=True),
    sa.Column('temperature_min', sa.Float(), nullable=True),
    sa.Column('temperature_ideal_min', sa.Float(), nullable=True),
    sa.Column('temperature_ideal_max', sa.Float(), nullable=True),
    sa.Column('temperature_max', sa.Float(), nullable=True),
    sa.Column('humidity_min', sa.Float(), nullable=True),
    sa.Column('humidity_ideal_min', sa.Float(), nullable=True),
    sa.Column('humidity_ideal_max', sa.Float(), nullable=True),
    sa.Column('humidity_max', sa.Float(), nullable=True),
    sa.Column('light_requirement', sa.String(length=100), nullable=True),
    sa.Column('sunlight_hours_min', sa.Float(), nullable=True),
    sa.Column('sunlight_hours_ideal', sa.Float(), nullable=True),
    sa.Column('sunlight_hours_max', sa.Float(), nullable=True),
    sa.Column('watering_frequency_min_days', sa.Integer(), nullable=True),
    sa.Column('watering_frequency_max_days', sa.Integer(), nullable=True),
    sa.Column('preferred_moisture_min', sa.Float(), nullable=True),
    sa.Column('preferred_moisture_max', sa.Float(), nullable=True),
    sa.Column('drought_tolerance', sa.String(length=50), nullable=True),
    sa.Column('overwatering_sensitivity', sa.String(length=50), nullable=True),
    sa.Column('preferred_soil_types', sa.JSON(), nullable=True),
    sa.Column('drainage_requirement', sa.String(length=100), nullable=True),
    sa.Column('moisture_retention', sa.String(length=100), nullable=True),
    sa.Column('ph_min', sa.Float(), nullable=True),
    sa.Column('ph_max', sa.Float(), nullable=True),
    sa.Column('preferred_pot_size', sa.String(length=50), nullable=True),
    sa.Column('pot_drainage_required', sa.Boolean(), nullable=True),
    sa.Column('repotting_interval', sa.String(length=100), nullable=True),
    sa.Column('growth_stages', sa.JSON(), nullable=True),
    sa.Column('growth_rate', sa.String(length=50), nullable=True),
    sa.Column('mature_size', sa.String(length=100), nullable=True),
    sa.Column('fertilizer_type', sa.String(length=100), nullable=True),
    sa.Column('fertilizer_frequency', sa.String(length=100), nullable=True),
    sa.Column('seasonal_care', sa.JSON(), nullable=True),
    sa.Column('common_problems', sa.JSON(), nullable=True),
    sa.Column('care_guidelines', sa.JSON(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plant_species_category'), 'plant_species', ['category'], unique=False)
    op.create_index(op.f('ix_plant_species_common_name'), 'plant_species', ['common_name'], unique=False)
    op.create_table('users',
    sa.Column('id', database.base.GUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('experience_level', sa.String(length=50), nullable=True),
    sa.Column('care_preference', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('plant_experiences',
    sa.Column('id', database.base.GUID(), nullable=False),
    sa.Column('plant_species_id', database.base.GUID(), nullable=False),
    sa.Column('condition', sa.String(length=100), nullable=False),
    sa.Column('recommendation_type', sa.String(length=100), nullable=False),
    sa.Column('observed_outcome', sa.String(length=100), nullable=True),
    sa.Column('sample_count', sa.Integer(), nullable=False),
    sa.Column('success_count', sa.Integer(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['plant_species_id'], ['plant_species.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plant_experiences_plant_species_id'), 'plant_experiences', ['plant_species_id'], unique=False)
    op.create_table('plant_symptoms',
    sa.Column('id', database.base.GUID(), nullable=False),
    sa.Column('plant_species_id', database.base.GUID(), nullable=True),
    sa.Column('symptom_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('possible_causes', sa.JSON(), nullable=True),
    sa.Column('severity', sa.String(length=50), nullable=True),
    sa.Column('diagnostic_questions', sa.JSON(), nullable=True),
    sa.Column('recommended_actions', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['plant_species_id'], ['plant_species.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plant_symptoms_plant_species_id'), 'plant_symptoms', ['plant_species_id'], unique=False)
    op.create_table('questionnaires',
    sa.Column('id', database.base.GUID(), nullable=False),
    sa.Column('plant_species_id', database.base.GUID(), nullable=True),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['plant_species_id'], ['plant_species.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questionnaires_plant_species_id'), 'questionnaires', ['plant_species_id'], unique=False)
    op.create_table('user_plants',
    sa.Column('id', database.base.GUID(), nullable=False),
    sa.Column('user_id', database.base.GUID(), nullable=False),
    sa.Column('plant_species_id', database.base.GUID(), nullable=True),
    sa.Column('nickname', sa.String(length=255), nullable=False),
    sa.Column('date_added', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('growth_stage', sa.String(length=50), nullable=True),
    sa.Column('soil_type', sa.String(length=50), nullable=True),
    sa.Column('pot_size', sa.String(length=50), nullable=True),
    sa.Column('location_description', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['plant_species_id'], ['plant_species.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_plants_plant_species_id'), 'user_plants', ['plant_species_id'], unique=False)
    op.create_index(op.f('ix_user_plants_user_id'), 'user_plants', ['user_id'], unique=False)
    op.create_table('assessments',
    sa.Column('id', database.base.GUID(), nullable=False),
    sa.Column('user_plant_id', database.base.GUID(), nullable=False),
    sa.Column('health_score', sa.Float(), nullable=True),
    sa.Column('water_needed', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.String(length=50), nullable=True),
    sa.Column('answers', sa.JSON(), nullable=True),
    sa.Column('ml_inputs', sa.JSON(), nullable=True),
    sa.Column('ml_output', sa.JSON(), nullable=True),
    sa.Column('recommendations', sa.JSON(), nullable=True),
    sa.Column('ai_explanation', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_plant_id'], ['user_plants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assessments_user_plant_id'), 'assessments', ['user_plant_id'], unique=False)
    op.create_table('questions',
    sa.Column('id', database.base.GUID(), nullable=False),
    sa.Column('questionnaire_id', database.base.GUID(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('question_type', sa.String(length=50), nullable=False),
    sa.Column('question_order', sa.Integer(), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('maps_to_feature', sa.String(length=100), nullable=True),
    sa.Column('conditional_rule', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['questionnaire_id'], ['questionnaires.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questions_questionnaire_id'), 'questions', ['questionnaire_id'], unique=False)
    op.create_table('assessment_answers',
    sa.Column('id', database.base.GUID(), nullable=False),
    sa.Column('assessment_id', database.base.GUID(), nullable=False),
    sa.Column('question_id', database.base.GUID(), nullable=True),
    sa.Column('answer_value', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assessment_answers_assessment_id'), 'assessment_answers', ['assessment_id'], unique=False)
    op.create_index(op.f('ix_assessment_answers_question_id'), 'assessment_answers', ['question_id'], unique=False)
    op.create_table('feedback',
    sa.Column('id', database.base.GUID(), nullable=False),
    sa.Column('assessment_id', database.base.GUID(), nullable=False),
    sa.Column('user_id', database.base.GUID(), nullable=True),
    sa.Column('helpful', sa.Boolean(), nullable=False),
    sa.Column('outcome', sa.String(length=100), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_assessment_id'), 'feedback', ['assessment_id'], unique=False)
    op.create_index(op.f('ix_feedback_user_id'), 'feedback', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feedback_user_id'), table_name='feedback')
    op.drop_index(op.f('ix_feedback_assessment_id'), table_name='feedback')
    op.drop_table('feedback')
    op.drop_index(op.f('ix_assessment_answers_question_id'), table_name='assessment_answers')
    op.drop_index(op.f('ix_assessment_answers_assessment_id'), table_name='assessment_answers')
    op.drop_table('assessment_answers')
    op.drop_index(op.f('ix_questions_questionnaire_id'), table_name='questions')
    op.drop_table('questions')
    op.drop_index(op.f('ix_assessments_user_plant_id'), table_name='assessments')
    op.drop_table('assessments')
    op.drop_index(op.f('ix_user_plants_user_id'), table_name='user_plants')
    op.drop_index(op.f('ix_user_plants_plant_species_id'), table_name='user_plants')
    op.drop_table('user_plants')
    op.drop_index(op.f('ix_questionnaires_plant_species_id'), table_name='questionnaires')
    op.drop_table('questionnaires')
    op.drop_index(op.f('ix_plant_symptoms_plant_species_id'), table_name='plant_symptoms')
    op.drop_table('plant_symptoms')
    op.drop_index(op.f('ix_plant_experiences_plant_species_id'), table_name='plant_experiences')
    op.drop_table('plant_experiences')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_plant_species_common_name'), table_name='plant_species')
    op.drop_index(op.f('ix_plant_species_category'), table_name='plant_species')
    op.drop_table('plant_species')
    # ### end Alembic commands ###
